layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

linkedin: https://www.linkedin.com/in/ryanmchang
location: https://goo.gl/maps/d9y5TrpMXi82

worked:
  - name: Oregon Career Information System
    web_url: https://oregoncis.uoregon.edu
    image_url: /assets/images/CIS.png
    description: The Oregon Career Information System (Oregon CIS) provides a system of occupational and educational information to help Oregonians learn about the world of work and education. I am part of a small team that is responsible for all aspects of development, including the front/back end, database design/maintenance, continuous integration, server maintenance, and general office IT.<br/><br/>Oregon CIS uses C# and ASP.NET, HTML5, CSS, JavaScript, and TeamCity CI along with Gulp.

  - name: Actively Learning
    web_url: https://activelylearning.org
    image_url: /assets/images/AL.png
    description: Actively Learning is the data collection app for a federally funded research project to examine the correlation of active learning with grit growth and student success and retention in engineering students at Cal Poly, San Luis Obispo. I developed the Android app and app backend. The app backend is based on the open-source Parse Platform. Another developer developed the iOS app, and I took over its continued development and maintenance after the initial version was completed.<br/><br/>Actively Learning uses Java and the Android SDK, Swift, Parse Platform, and NodeJS.

topics:
  - name: VMware vSphere
    image_url: /assets/images/vsphere.png
    description: In my free time, I enjoy learning about and practicing system administration functions at home. Virtualization and VMware ESXi is the foundation of my home "datacenter". Virtualization allows me to rapidly experiment with new technologies and develop methods to apply the technologies at work.

  - name: Windows Media Center
    web_url: https://thegreenbutton.tv
    image_url: /assets/images/wmc.png
    description: I seem to spend more time maintaining and improving my DVR system, which is built on Windows Media Center. The pursuit of the perfect DVR system is what initially got me into virtualization. I'm continually researching other ways to watch television, such as Plex/Emby and Android TV.

  - name: Apple
    image_url: /assets/images/apple.png
    description: When I was younger, I was very good at troubleshooting and repairing Mac computers. While I don't repair computers anymore, I still follow Apple closely and enjoy using Apple products. It's interesting how I'm currently a C#/ASP.NET and Android developer after being an Apple fan for so long. 