layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

linkedin: https://www.linkedin.com/in/ryanmchang

worked:
  - name: Oregon Career Information System
    web_url: https://oregoncis.uoregon.edu
    image_url: /assets/images/CIS.png
    description: The Oregon Career Information System (CIS) provides a system of occupational and educational information to help Oregonians learn about the world of work and education.

  - name: Actively Learning
    web_url: https://activelylearning.org
    image_url: /assets/images/AL.png
    description: Actively Learning is the data collection app for a federally funded research project to measure Grit in students at Cal Poly, San Luis Obispo.

topics:
  - name: VMware vSphere
    image_url: /assets/images/vsphere.png
    description: In my free time, I enjoy learning about and practicing system administration functions at home. Virtualization and VMware ESXi is the foundation of my home "datacenter". Virtualization allows me to rapidly experiment with new technologies and develop methods to apply the technologies at work.

  - name: Windows Media Center
    web_url: https://thegreenbutton.tv
    image_url: /assets/images/wmc.png
    description: I seem to spend more time maintaining and improving my DVR system, which is built on Windows Media Center. I'm continually researching other ways to watch television, such as Plex/Emby and Android TV.